(function initElarionDefaults(global) {
  const DEFAULT_SETTINGS = {
    enabled: true,
    mode: "hide",
    blockAds: true,
    blockAiFeatures: true,
    heuristicDetection: true,
    heuristicThreshold: 7,
    debugOverlay: false,
    disabledSites: [],
    allowlist: [],
    customTextRules: [],
    customSelectorRules: [],
    customDomainRules: []
  };

  const SITE_RULES = [
    {
      id: "google-ai-overview",
      hostIncludes: ["google."],
      selectors: [
        "[aria-label*='AI Overview' i]",
        "[data-attrid*='AIOverview' i]",
        "div:has-text('AI Overview')"
      ],
      textPatterns: ["AI Overview", "Search Labs"]
    },
    {
      id: "bing-copilot",
      hostIncludes: ["bing.com"],
      selectors: [
        "[aria-label*='Copilot' i]",
        "[class*='b_syd' i]",
        "[id*='copilot' i]"
      ],
      textPatterns: ["Copilot", "AI-powered"]
    },
    {
      id: "linkedin-ai",
      hostIncludes: ["linkedin.com"],
      selectors: [
        "[aria-label*='AI' i]",
        "[data-test-id*='ai' i]",
        ".feed-shared-update-v2:has-text('AI')"
      ],
      textPatterns: ["Rewrite with AI", "Try Premium AI", "AI-powered"]
    },
    {
      id: "reddit-ai",
      hostIncludes: ["reddit.com"],
      selectors: [
        "[data-testid*='ai' i]",
        "[aria-label*='AI' i]"
      ],
      textPatterns: ["AI summary", "summarized by AI"]
    },
    {
      id: "medium-ai",
      hostIncludes: ["medium.com"],
      selectors: [
        "article:has-text('generated by AI')",
        "[class*='ai' i]"
      ],
      textPatterns: ["generated by AI", "AI-assisted"]
    },
    {
      id: "pinterest-ai-content",
      hostIncludes: ["pinterest."],
      selectorRequiresEvidence: true,
      selectors: [
        "[data-test-id='pin']",
        "[data-test-id='pinWrapper']",
        "[data-test-id='closeup-main-pin']",
        "[data-test-id*='pin' i]"
      ],
      textPatterns: [
        "Promoted",
        "Sponsored",
        "AI generated",
        "AI-generated",
        "AI art",
        "AI image",
        "AI portrait",
        "AI model",
        "AI influencer",
        "generated by AI",
        "made with AI",
        "created with AI",
        "Midjourney",
        "Stable Diffusion",
        "DALL-E",
        "DALL·E",
        "Leonardo AI",
        "Runway ML",
        "ComfyUI",
        "prompt:"
      ],
      sourceDomains: [
        "openart.ai",
        "civitai.com",
        "lexica.art",
        "nightcafe.studio",
        "playgroundai.com",
        "seaart.ai",
        "tensor.art",
        "krea.ai",
        "leonardo.ai",
        "midjourney.com",
        "stablediffusionweb.com"
      ]
    }
  ];

  const GENERIC_AI_TEXT_PATTERNS = [
    "AI Overview",
    "Ask AI",
    "generated by AI",
    "AI-generated",
    "AI summary",
    "summarized by AI",
    "written with AI",
    "AI-powered",
    "AI art",
    "AI image",
    "AI-generated image",
    "created with AI",
    "made with AI",
    "Midjourney",
    "Stable Diffusion",
    "DALL-E",
    "DALL·E",
    "Leonardo AI",
    "Runway ML",
    "ComfyUI",
    "ChatGPT",
    "Copilot"
  ];

  const GENERIC_AD_SELECTORS = [
    "[id^='ad-']",
    "[id*='-ad-']",
    "[id*='ads']",
    "[class*=' ad-']",
    "[class*=' ads']",
    "[class*='advert']",
    "[aria-label*='advertisement' i]",
    "[aria-label*='sponsored' i]",
    "[aria-label*='promoted' i]",
    "[data-test-id*='promoted' i]",
    "[data-test-id*='sponsored' i]",
    "ins.adsbygoogle",
    "iframe[src*='doubleclick']",
    "iframe[src*='googlesyndication']",
    "iframe[src*='adservice']"
  ];

  const AI_HEURISTIC_PHRASES = [
    "in today's fast-paced world",
    "delve into",
    "it's important to note",
    "it is important to note",
    "whether you're",
    "unlock the power",
    "game-changer",
    "seamlessly",
    "robust solution",
    "ever-evolving",
    "navigating the complexities",
    "not only",
    "but also",
    "in conclusion",
    "ultimately",
    "furthermore",
    "moreover"
  ];

  global.ELARION_DEFAULTS = {
    DEFAULT_SETTINGS,
    SITE_RULES,
    GENERIC_AI_TEXT_PATTERNS,
    GENERIC_AD_SELECTORS,
    AI_HEURISTIC_PHRASES
  };
})(globalThis);
