(function initElarionDefaults(global) {
  const DEFAULT_SETTINGS = {
    enabled: true,
    mode: "hide",
    blockAds: true,
    blockAiFeatures: true,
    heuristicDetection: true,
    heuristicThreshold: 7,
    debugOverlay: false,
    blockAdNetwork: true,
    blockPopups: true,
    disabledSites: [],
    allowlist: [],
    customTextRules: [],
    customSelectorRules: [],
    customDomainRules: [],
    // Per-site actions for the "ad" and "ai" categories. Values: hide,
    // blur, label, off, or default (= use the global mode). Keys match
    // the host and its subdomains.
    sitePresets: {
      "pinterest.com": { adAction: "hide", aiAction: "label" },
      "google.com": { aiAction: "hide" },
      "bing.com": { aiAction: "hide" },
      "reddit.com": { aiAction: "label" },
      "linkedin.com": { aiAction: "hide" },
      "medium.com": { aiAction: "label" }
    }
  };

  const SITE_RULES = [
    {
      id: "google-ai-overview",
      hostIncludes: ["google."],
      selectors: [
        "[aria-label*='AI Overview' i]",
        "[data-attrid*='AIOverview' i]",
        "div:has-text('AI Overview')"
      ],
      textPatterns: ["AI Overview", "Search Labs"]
    },
    {
      id: "bing-copilot",
      hostIncludes: ["bing.com"],
      selectors: [
        "[aria-label*='Copilot' i]",
        "[class*='b_syd' i]",
        "[id*='copilot' i]"
      ],
      textPatterns: ["Copilot", "AI-powered"]
    },
    {
      id: "linkedin-ai",
      hostIncludes: ["linkedin.com"],
      selectors: [
        "[aria-label*='AI' i]",
        "[data-test-id*='ai' i]",
        ".feed-shared-update-v2:has-text('AI')"
      ],
      textPatterns: ["Rewrite with AI", "Try Premium AI", "AI-powered"]
    },
    {
      id: "reddit-ai",
      hostIncludes: ["reddit.com"],
      selectors: [
        "[data-testid*='ai' i]",
        "[aria-label*='AI' i]"
      ],
      textPatterns: ["AI summary", "summarized by AI"]
    },
    {
      id: "medium-ai",
      hostIncludes: ["medium.com"],
      selectors: [
        "article:has-text('generated by AI')",
        "[class*='ai' i]"
      ],
      textPatterns: ["generated by AI", "AI-assisted"]
    },
    {
      id: "youtube-ads",
      category: "ad",
      hostIncludes: ["youtube.com"],
      selectors: [
        "ytd-display-ad-renderer",
        "ytd-in-feed-ad-layout-renderer",
        "ytd-ad-slot-renderer",
        "ytd-banner-promo-renderer",
        "ytd-player-legacy-desktop-watch-ads-renderer",
        "ytd-promoted-sparkles-web-renderer",
        "ytd-promoted-video-renderer",
        "ytd-companion-slot-renderer",
        "#masthead-ad",
        "#player-ads"
      ],
      textPatterns: []
    },
    {
      id: "twitch-promoted",
      category: "ad",
      hostIncludes: ["twitch.tv"],
      selectors: [
        "[data-a-target*='promoted' i]",
        "[data-a-target*='sponsored' i]"
      ],
      textPatterns: []
    },
    {
      id: "pinterest-promoted",
      category: "ad",
      hostIncludes: ["pinterest."],
      selectorRequiresEvidence: true,
      selectors: [
        "[data-test-id='pin']",
        "[data-test-id='pinWrapper']",
        "[data-test-id='closeup-main-pin']",
        "[data-test-id*='pin' i]"
      ],
      textPatterns: ["Promoted", "Sponsored"]
    },
    {
      id: "pinterest-ai-content",
      category: "ai",
      hostIncludes: ["pinterest."],
      selectorRequiresEvidence: true,
      selectors: [
        "[data-test-id='pin']",
        "[data-test-id='pinWrapper']",
        "[data-test-id='closeup-main-pin']",
        "[data-test-id*='pin' i]"
      ],
      textPatterns: [
        "AI generated",
        "AI-generated",
        "AI art",
        "AI image",
        "AI portrait",
        "AI model",
        "AI influencer",
        "generated by AI",
        "made with AI",
        "created with AI",
        "Midjourney",
        "Stable Diffusion",
        "DALL-E",
        "DALL·E",
        "Leonardo AI",
        "Runway ML",
        "ComfyUI",
        "prompt:"
      ],
      sourceDomains: [
        "openart.ai",
        "civitai.com",
        "lexica.art",
        "nightcafe.studio",
        "playgroundai.com",
        "seaart.ai",
        "tensor.art",
        "krea.ai",
        "leonardo.ai",
        "midjourney.com",
        "stablediffusionweb.com"
      ]
    }
  ];

  const GENERIC_AI_TEXT_PATTERNS = [
    "AI Overview",
    "Ask AI",
    "generated by AI",
    "AI-generated",
    "AI summary",
    "summarized by AI",
    "written with AI",
    "AI-powered",
    "AI art",
    "AI image",
    "AI-generated image",
    "created with AI",
    "made with AI",
    "Midjourney",
    "Stable Diffusion",
    "DALL-E",
    "DALL·E",
    "Leonardo AI",
    "Runway ML",
    "ComfyUI",
    "ChatGPT",
    "Copilot"
  ];

  // Keep these anchored: bare substrings like [id*='ads'] match innocent
  // ids ("uploads", "threads"), and [class*=' ad-'] matched YouTube's
  // ad-showing state class on the whole video player.
  const GENERIC_AD_SELECTORS = [
    "[id^='ad-']",
    "[id*='-ad-']",
    "[id='ads']",
    "[id^='ads-']",
    "[id^='ads_']",
    "[id$='-ads']",
    "[id$='_ads']",
    "[id*='-ads-']",
    "[id^='google_ads']",
    "[class^='ad-']",
    "[class*='ad-banner']",
    "[class*='ad-container']",
    "[class*='ad-slot']",
    "[class*='ad-wrapper']",
    "[class*='ad-unit']",
    "[class*='ad-placement']",
    "[class*='advert']",
    "[aria-label*='advertisement' i]",
    "[aria-label*='sponsored' i]",
    "[aria-label*='promoted' i]",
    "[data-test-id*='promoted' i]",
    "[data-test-id*='sponsored' i]",
    "ins.adsbygoogle",
    "iframe[src*='doubleclick']",
    "iframe[src*='googlesyndication']",
    "iframe[src*='adservice']"
  ];

  // Pure ad-serving domains only. Never add CDNs or dual-use domains here:
  // these are blocked at the network level for every third-party request.
  const AD_NETWORK_DOMAINS = [
    "doubleclick.net",
    "googlesyndication.com",
    "googleadservices.com",
    "adnxs.com",
    "rubiconproject.com",
    "flashtalking.com",
    "criteo.com",
    "criteo.net",
    "taboola.com",
    "outbrain.com",
    "pubmatic.com",
    "openx.net",
    "amazon-adsystem.com",
    "smartadserver.com",
    "adform.net",
    "propellerads.com",
    "propellerclick.com",
    "onclickads.net",
    "popads.net",
    "popcash.net",
    "adsterra.com",
    "hilltopads.net",
    "exoclick.com",
    "clickadu.com",
    "adcash.com",
    "trafficjunky.com",
    "juicyads.com",
    "mgid.com"
  ];

  // Phrases used by full-page scam/install interstitials ("Attention: to
  // display this content properly please activate ..."). Matched only on
  // large high-z-index overlay elements, never on normal page content.
  const INTERSTITIAL_TEXT_PATTERNS = [
    "to display this content",
    "please activate",
    "press allow",
    "click allow",
    "allow notifications",
    "you have won",
    "your download is ready",
    "your device is infected",
    "virus detected"
  ];

  const AI_HEURISTIC_PHRASES = [
    "in today's fast-paced world",
    "delve into",
    "it's important to note",
    "it is important to note",
    "whether you're",
    "unlock the power",
    "game-changer",
    "seamlessly",
    "robust solution",
    "ever-evolving",
    "navigating the complexities",
    "not only",
    "but also",
    "in conclusion",
    "ultimately",
    "furthermore",
    "moreover"
  ];

  global.ELARION_DEFAULTS = {
    DEFAULT_SETTINGS,
    SITE_RULES,
    GENERIC_AI_TEXT_PATTERNS,
    GENERIC_AD_SELECTORS,
    AD_NETWORK_DOMAINS,
    INTERSTITIAL_TEXT_PATTERNS,
    AI_HEURISTIC_PHRASES
  };
})(globalThis);
